import 'package:flutter/material.dart';
const white=Colors.white;
const black=Colors.black;
const blue=Colors.blue;
const orange=Colors.orange;
const pink=Colors.pink;
const grey=Colors.grey;
const green=Colors.green;
const red=Colors.red;